### ISSUE TITLE
[3.0 Beta] Using Next.js version 14.2.1 results in an error

### ISSUE THREAD

**Issue by todor0v** [payloadcms/payload-3.0-demo#113]
### Describe the Bug

When trying to log in after installing Payload using `npx create-payload-app@beta` on an existing project with Next.js version `14.2.1` I get the following error:

```
createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
```

Then I get a `GET /api/users/me` returning 500.

**The error is not present** if I use Next.js `14.2.0-canary.23` like the 3.0 Demo.

### To Reproduce

Install Payload on an existing project using Next.js 14.2.1 and try to login or register a user.

### Payload Version

3.0.0-beta.10

### Adapters and Plugins

db-mongodb, next, richtext-lexical

**Comment by todor0v** [comment]
@jmikrut That is correct. The issue is only present if I use `next dev --turbo`.

**Comment by jmikrut** [comment]
Hey @todor0v — looks like they fixed the issue, but the fix has not yet been released as a canary. I'll keep this open until we see confirmation that the fix works in a released Next.js canary.

**Comment by todor0v** [comment]
@jmikrut Thank you so much! 🙏

**Comment by KnotScientific** [comment]
@jmikrut @todor0v was this fixed in 14.3.0-canary.8 or 14.3.0-canary.7? I see the fix as part of the commits, but after installing 14.3.0-canary.8 and  running next dev --turbo. I'm still running into the same issue.
![Screenshot 2024-04-17 at 6 03 03 PM](https://github.com/payloadcms/payload-3.0-demo/assets/29667155/fa257b33-3d85-4e69-8b90-f220ab527da8)

**Comment by luochuanyuewu** [comment]
> @jmikrut @todor0v was this fixed in 14.3.0-canary.8 or 14.3.0-canary.7? I see the fix as part of the commits, but after installing 14.3.0-canary.8 and running next dev --turbo. I'm still running into the same issue. ![Screenshot 2024-04-17 at 6 03 03 PM](https://private-user-images.githubusercontent.com/29667155/323390765-fa257b33-3d85-4e69-8b90-f220ab527da8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDMzMjEsIm5iZiI6MTcxMzQwMzAyMSwicGF0aCI6Ii8yOTY2NzE1NS8zMjMzOTA3NjUtZmEyNTdiMzMtM2Q4NS00ZTY5LThiOTAtZjIyMGFiNTI3ZGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAxMTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNzg5ODhjMGRkOGMyYzM0NDMzMDQ4MDNjNWRmNWFmM2NlODE0ZmU0M2Y0NWQyYWE5NWMxMDU4NGZkZmE2MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gVpfZXrOzeWajA6gNYspx_o3L5_BOmB5bw-xXRP_IeM)

Me on the same page.

**Comment by todor0v** [comment]
@luochuanyuewu As far as I can see not yet. I still get the same error using Payload `3.0.0-beta.10` (or 11) and Next.js `14.3.0-canary-11`

**Comment by jmikrut** [comment]
Happy to report that this is now fixed!
